##EDA

##Initial Data Inception & Structure

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
data=pd.read_csv("/content/wasla_customer_records.csv")
data

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [ ]:
print(f'Data shape: {data.shape}')
print(f'\nDATA types & NON-Null counts : \n')
print(data.info())

Data shape: (7043, 21)

DATA types & NON-Null counts :

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB
None

##Target Class Imbalance & The Accuracy Trap

In [ ]:
churn_count = data['Churn'].value_counts()
churn_rate=data['Churn'].value_counts(normalize=True) *100

print(f'Churn Count: \n{churn_count}\n')
print(f'Churn Rate: \n{churn_rate}')

Churn Count:
Churn
No     5174
Yes    1869
Name: count, dtype: int64

Churn Rate:
Churn
No     73.463013
Yes    26.536987
Name: proportion, dtype: float64

## Uncovering Hidden data Quricks(TOTALCharages Issue)

In [ ]:
print(f'Technical missing value : \n {data.isna().sum()}')

Technical missing value :
 customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [ ]:
try:
  data['TotalCharges'].astype(float)
except ValueError as e:
  print(f'[Expected Error caught!]: {e}')

empty_spaces =data[data['TotalCharges']==' ']
print(f'\nFound {len(empty_spaces)} rows with empty string in TotalCharge \n')

print(empty_spaces[['customerID','tenure','MonthlyCharges','TotalCharges']])

[Expected Error caught!]: could not convert string to float: ' '

Found 11 rows with empty string in TotalCharge

      customerID  tenure  MonthlyCharges TotalCharges
488   4472-LVYGI       0           52.55
753   3115-CZMZD       0           20.25
936   5709-LVOEQ       0           80.85
1082  4367-NUYAO       0           25.75
1340  1371-DWPAZ       0           56.05
3331  7644-OMVMY       0           19.85
3826  3213-VVOLG       0           25.35
4380  2520-SGTTA       0           20.00
5218  2923-ARZLG       0           19.70
6670  4075-WKNIU       0           73.35
6754  2775-SEFEE       0           61.90

##Preprocessing & Feature Engineerging

##Data Cleaning & Standarization

In [ ]:
df_clean = data.copy()

In [ ]:
df_clean['TotalCharges'] = df_clean['TotalCharges'].replace(' ', np.nan).astype(float)
df_clean['TotalCharges'].fillna(0, inplace=True)

/tmp/ipykernel_28218/89583284.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_clean['TotalCharges'].fillna(0, inplace=True)

In [ ]:
df_clean['SeniorCitizen'] = df_clean['SeniorCitizen'].map({1 :'Yes' , 0 : 'No'})

In [ ]:
print(f'TotalCharge Nulls after cleaning : {df_clean['TotalCharges'].isnull().sum()}')
print(f'SeniorCitizen unique values: {df_clean['SeniorCitizen'].unique()}')

TotalCharge Nulls after cleaning : 0
SeniorCitizen unique values: ['No' 'Yes']

##Domain_Specific Feature Engineering

In [ ]:
# 1.tenure_Bucket
def get_teunre_bucket(tenure):
  if tenure <= 12:
    return '0-12 Months'
  elif tenure <= 24:
    return '13-24 Months'
  elif tenure <= 48:
    return '25-48 Months'
  else:
    return '48+ Months'

df_clean['tenure_bucket'] = df_clean['tenure'].apply(get_teunre_bucket)

In [ ]:
# 2.Num_Services (Sticky_Customer)
service_cols =['OnlineSecurity','OnlineBackup','DeviceProtection','TechSupport','StreamingTV','StreamingMovies']
df_clean['num_Services'] = (df_clean[service_cols]=='Yes').sum(axis=1)

In [ ]:
# 3.Has_family
df_clean['has_family'] = np.where((df_clean['Dependents']=='Yes') | (df_clean['Partner']=='Yes'),'Yes','No')

In [ ]:
df_clean[['tenure','tenure_bucket','num_Services','has_family']].head()

   tenure tenure_bucket  num_Services has_family
0       1   0-12 Months             1        Yes
1      34  25-48 Months             2         No
2       2   0-12 Months             2         No
3      45  25-48 Months             3         No
4       2   0-12 Months             0         No

##Categorical Encoding & Train/Test Split

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder
from sklearn.compose import ColumnTransformer

In [ ]:
X=df_clean.drop(columns=["Churn","customerID"])
y=df_clean['Churn'].map({'Yes':1,'No':0})

In [ ]:
X_train , X_test , y_train , y_test = train_test_split(X,y,test_size=0.2,random_state=42,stratify=y)

In [ ]:
categorical_cols = X.select_dtypes(include=['object','category']).columns.tolist()
numeric_cols = X.select_dtypes(include=['int64','float64']).columns.tolist()

In [ ]:
preprocessor = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(drop='first',handle_unknown='ignore'), categorical_cols),
        ('num', StandardScaler(), numeric_cols)
    ])

In [ ]:
print(f'X_train shape: {X_train.shape}')
print(f'X_test shape: {X_test.shape}')

X_train shape: (5634, 22)
X_test shape: (1409, 22)

##Multi_Model Training & Tuning

###Baseline Models (Logistic Regression vs Random Forest)

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import recall_score , roc_auc_score

In [ ]:
#1.Logisitic Regression
pip_lr = Pipeline([
    ('preprocessor',preprocessor),
    ('classifier',LogisticRegression(max_iter=1000,random_state=42))
])

In [ ]:
#2.random forest iepline
pip_rf = Pipeline([
    ('preprocessor',preprocessor),
    ('classifier',RandomForestClassifier(random_state=42))
])

In [ ]:
pip_lr.fit(X_train,y_train)
pip_rf.fit(X_train,y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('cat',
                                                  OneHotEncoder(drop='first',
                                                                handle_unknown='ignore'),
                                                  ['gender', 'SeniorCitizen',
                                                   'Partner', 'Dependents',
                                                   'PhoneService',
                                                   'MultipleLines',
                                                   'InternetService',
                                                   'OnlineSecurity',
                                                   'OnlineBackup',
                                                   'DeviceProtection',
                                                   'TechSupport', 'StreamingTV',
                                                   'StreamingMovies',
                                                   'Contract',
                                                   'PaperlessBilling',
                                                   'PaymentMethod',
                                                   'tenure_bucket',
                                                   'has_family']),
                                                 ('num', StandardScaler(),
                                                  ['tenure', 'MonthlyCharges',
                                                   'TotalCharges',
                                                   'num_Services'])])),
                ('classifier', RandomForestClassifier(random_state=42))])

In [ ]:
print(f'Logistic Regression Train Recall: {recall_score(y_train,pip_lr.predict(X_train))}')
print(f'random Forest Train Recall: {recall_score(y_train,pip_rf.predict(X_train))}')

Logistic Regression Train Recall: 0.5418060200668896
random Forest Train Recall: 0.9953177257525083

In [ ]:
from xgboost import XGBClassifier
from sklearn.model_selection import GridSearchCV

pipe_xgb = Pipeline([
    ('preprocessor', preprocessor),
    ('classifier', XGBClassifier(random_state=42, eval_metric='logloss'))
])

param_grid = {
    'classifier__n_estimators': [50, 100],
    'classifier__max_depth': [3, 5],
    'classifier__learning_rate': [0.01, 0.1],
    'classifier__scale_pos_weight': [1, 3] # more weight for the churn category
}

grid_xgb = GridSearchCV(pipe_xgb, param_grid, cv=3, scoring='recall', n_jobs=-1)
grid_xgb.fit(X_train, y_train)

print("Best Parameters:", grid_xgb.best_params_)
print("Best CV Recall Score:", grid_xgb.best_score_)

Best Parameters: {'classifier__learning_rate': 0.01, 'classifier__max_depth': 3, 'classifier__n_estimators': 50, 'classifier__scale_pos_weight': 3}
Best CV Recall Score: 0.8688997808200067

## Model Selection & Mona Adel Client Report

### Evaluating Beyond Accuracy (Recall, Precision, ROC-AUC)

In [ ]:
from sklearn.metrics import classification_report, roc_auc_score, confusion_matrix

models = {
    'Logistic Regression': pip_lr,
    'Random Forest': pip_rf,
    'Tuned XGBoost': grid_xgb.best_estimator_
}

for name, model in models.items():
    preds = model.predict(X_test)
    probs = model.predict_proba(X_test)[:, 1]

    print(f"\n================ {name} ================")
    print("ROC-AUC Score:", roc_auc_score(y_test, probs))
    print("Recall (Churn Class):", recall_score(y_test, preds))
    print("Confusion Matrix:\n", confusion_matrix(y_test, preds))

================ Logistic Regression ================
ROC-AUC Score: 0.842336407553799
Recall (Churn Class): 0.5187165775401069
Confusion Matrix:
 [[933 102]
 [180 194]]

================ Random Forest ================
ROC-AUC Score: 0.8185292825957787
Recall (Churn Class): 0.47058823529411764
Confusion Matrix:
 [[928 107]
 [198 176]]

================ Tuned XGBoost ================
ROC-AUC Score: 0.821261205404428
Recall (Churn Class): 0.8502673796791443
Confusion Matrix:
 [[677 358]
 [ 56 318]]

### Translating ML Metrics into Mona Adel's Client Report

In [ ]:
best_model = grid_xgb.best_estimator_.named_steps['classifier']
ohe_cols = grid_xgb.best_estimator_.named_steps['preprocessor'].named_transformers_['cat'].get_feature_names_out(categorical_cols).tolist()
all_features = numeric_cols + ohe_cols

importances = pd.Series(best_model.feature_importances_, index=all_features).sort_values(ascending=False)

plt.figure(figsize=(8, 6))
importances.head(10).plot(kind='barh', color='teal')
plt.title('Top 10 Drivers of Customer Churn - Wasla Telecom')
plt.gca().invert_yaxis()
plt.xlabel('Relative Importance')
plt.show()